force-app/main/default/objects/OpenAI_Assistant__mdt/OpenAI_Assistant__mdt.object-meta.xml
<CustomObject>
    <label>OpenAI Assistant</label>
    <pluralLabel>OpenAI Assistants</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpenAI_Assistant__mdt/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <label>External Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpenAI_Assistant__mdt/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>gpt-4-turbo-preview</fullName>
                <default>true</default>
                <label>gpt-4-turbo-preview</label>
            </value>
            <value>
                <fullName>gpt-4</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <label>Thread</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Thread Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/Assistant_Name__c.field-meta.xml
<CustomField>
    <fullName>Assistant_Name__c</fullName>
    <label>Assistant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gpt-4</fullName>
            </value>
            <value>
                <fullName>gpt-4-turbo-preview</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Run_Id__c.field-meta.xml
<CustomField>
    <fullName>Run_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Chat GPT External Id for a &quot;Run&quot;</inlineHelpText>
    <label>Run Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/Thread_Event__c.object-meta.xml
<CustomObject>
    <label>Thread Event</label>
    <nameField>
        <label>Thread Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thread Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread_Event__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Thread__c.field-meta.xml
<CustomField>
    <fullName>Thread__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meta</fullName>
                <default>true</default>
                <label>Meta</label>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ThreadService.cls
public with sharing class ThreadService {

    public ThreadWrapper createThread() {
        OpenAiThread serviceThread = new OpenAi().createThread();
        Thread__c t = new Thread__c(External_Id__c = serviceThread.id);
        insert t;

        return getThread(t.Id);
    }

    public ThreadWrapper routeThreadToAssistant(String threadId, String assistantName) {
        String threadExternalId = ThreadSelector.getThread(threadId)?.External_Id__c;
        String assistantExternalId = [SELECT External_Id__c FROM OpenAI_Assistant__mdt WHERE DeveloperName = :assistantName]?.External_Id__c;

        // calling open ai to set an assistant to the thread
        ThreadWrapper res = new ThreadWrapper(new OpenAi().setAssistant(threadExternalId, assistantExternalId));

        // saving updates from the run response
        update new Thread__c(
                Id = threadId,
                Assistant_Name__c = assistantName,
                Run_Id__c = res.runId,
                Model__c = res.model
        );

        return res;
    }

    public ThreadWrapper getThread(Id threadId) {
        Thread__c thread = ThreadSelector.getThread(threadId);
        return new ThreadWrapper(thread);
    }

    public ThreadEventWrapper postUserMessage(String salesforceThreadId, String userMessage) {
        Thread__c sfThread = [SELECT Id, External_Id__c FROM Thread__c WHERE Id = :salesforceThreadId];
        if (sfThread == null) {
            throw new ThreadServiceException('Unable To Find Salesforce Thread For: ' + salesforceThreadId);
        }

        String externalId = sfThread.External_Id__c;
        if (externalId == null) {
            throw new ThreadServiceException('Missing External Thread Id For: ' + salesforceThreadId);
        }

        OpenAiThreadMessage openAiMessage = new OpenAi().postMessage(externalId, userMessage);

        // saving the message to Salesforce
        Thread_Event__c te = new Thread_Event__c(
                Thread__c = salesforceThreadId,
                External_Id__c = openAiMessage.id,
                Type__c = 'Outbound',
                Body__c = userMessage
        );
        insert te;

        return new ThreadEventWrapper(ThreadSelector.getThreadEvent(te.Id));
    }

    public ThreadEventWrapper postUserMessageWithFiles(String salesforceThreadId, String userMessage, String[] fileIds) {
        Thread__c sfThread = [SELECT Id, External_Id__c FROM Thread__c WHERE Id = :salesforceThreadId];
        if (sfThread == null) {
            throw new ThreadServiceException('Unable To Find Salesforce Thread For: ' + salesforceThreadId);
        }

        String externalId = sfThread.External_Id__c;
        if (externalId == null) {
            throw new ThreadServiceException('Missing External Thread Id For: ' + salesforceThreadId);
        }

        OpenAiThreadMessage openAiMessage = new OpenAi().postMessage(externalId, userMessage, fileIds);

        // saving the message to Salesforce
        Thread_Event__c te = new Thread_Event__c(
                Thread__c = salesforceThreadId,
                External_Id__c = openAiMessage.id,
                Type__c = 'Outbound',
                Body__c = userMessage
        );
        insert te;

        return new ThreadEventWrapper(ThreadSelector.getThreadEvent(te.Id));
    }

    public ThreadEventWrapper checkThreadStatus(String salesforceThreadId) {
        Thread__c sfThread = [SELECT Id, External_Id__c, Run_Id__c FROM Thread__c WHERE Id = :salesforceThreadId];
        String threadRunResponse = new OpenAi().checkRunStatus(sfThread.External_Id__c, sfThread.Run_Id__c);
        ThreadEventWrapper threadEvent = new ThreadEventWrapper();
        threadEvent.salesforceId = salesforceThreadId;
        threadEvent.type = 'Meta';
        threadEvent.subtype = 'status_update';
        threadEvent.status = (String) ((Map<String, Object>) JSON.deserializeUntyped(threadRunResponse)).get('status');
        threadEvent.body = threadRunResponse;
        return threadEvent;
    }

    public ThreadEventWrapper[] getNewMessages(String salesforceThreadId) {
        Thread__c sfThread = [SELECT Id, External_Id__c, Run_Id__c FROM Thread__c WHERE Id = :salesforceThreadId];
        String messageResponse = new OpenAi().getMessages(sfThread.External_Id__c);
        System.debug('MessageResponse:' + messageResponse);
        Map<String, Object> root = (Map<String, Object>) JSON.deserializeUntyped(messageResponse);
        Object[] messages = (Object[]) root.get('data');
        Map<String, ThreadEventWrapper> newEventsByExternalId = new Map<String, ThreadEventWrapper>();

        for (Integer i = 0; i < messages.size(); i++) {
            Map<String, Object> message = (Map<String, Object>) messages[i];
            System.debug('Message: ' + JSON.serialize(message));
            String messageType = (String) message.get('object');
            String actorType = (String) message.get('role');

            ThreadEventWrapper eventWrapper = new ThreadEventWrapper();
            eventWrapper.threadId = salesforceThreadId;
            eventWrapper.actor = new ThreadEventWrapper.Actor(actorType);
            eventWrapper.externalId = (String) message.get('id');
            eventWrapper.eventTime = (Long) message.get('created_at');

            Object[] contents = (Object[]) message.get('content');
            eventWrapper.body = '';
            for (Integer c = 0; c < contents.size(); c++) {
                if (c > 0) {
                    eventWrapper.body += '\n\n';
                }
                Map<String, Object> contentMap = (Map<String, Object>) contents[c];
                Map<String, Object> contentText = (Map<String, Object>) contentMap.get('text');
                if (contentText != null) {
                    eventWrapper.body += (String) contentText.get('value');
                }
            }

            if (messageType == 'thread.message') {
                if (actorType == 'user') {
                    eventWrapper.type = 'Outbound';
                } else {
                    eventWrapper.type = 'Inbound';
                }
            } else {
                eventWrapper.type = 'Meta';
            }
            newEventsByExternalId.put(eventWrapper.externalId, eventWrapper);
        }

        Thread_Event__c[] currentEvents = [SELECT Id, External_Id__c FROM Thread_Event__c WHERE External_Id__c IN :newEventsByExternalId.keySet()];
        System.debug('CurrentEvents:' + JSON.serialize(currentEvents));
        if (currentEvents != null && !currentEvents.isEmpty()) {
            for (Integer i = 0; i < currentEvents.size(); i++) {
                ThreadEventWrapper removedEvent = newEventsByExternalId.remove(currentEvents[i].External_Id__c);
                System.debug('Removed Event: ' + JSON.serialize(removedEvent));
            }
        }

        ThreadEventWrapper[] createWrappers = newEventsByExternalId.values();
        System.debug('Need To Create Wrappers:' + JSON.serialize(createWrappers));
        if (createWrappers.isEmpty()) {
            return newEventsByExternalId.values();
        }

        Id[] newThreadEventIds = new List<Id>();
        for (Integer i = 0; i < createWrappers.size(); i++) {
            // splitting out the events that need to be created via the api and the rest that will be committed
            // everything else should have already just been created...
            // TODO: should probably change this to wait to create the message until it is received here...
            if (createWrappers[i].actor.role == 'assistant') {
                newThreadEventIds.add(ThreadEventService.createAsOpenAi(createWrappers[i].unwrap()));
            }
        }
        return ThreadEventWrapper.wrap(ThreadSelector.getThreadEvents(newThreadEventIds));
    }


    public class ThreadServiceException extends Exception {}
}