force-app/main/default/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <label>Thread</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Thread Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/Ended_At__c.field-meta.xml
<CustomField>
    <fullName>Ended_At__c</fullName>
    <label>Ended At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <inlineHelpText>User Feedback on Thread</inlineHelpText>
    <label>Feedback</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gpt-4</fullName>
            </value>
            <value>
                <fullName>gpt-4-turbo-preview</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Run_Id__c.field-meta.xml
<CustomField>
    <fullName>Run_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Chat GPT External Id for a &quot;Run&quot;</inlineHelpText>
    <label>Run Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thread_Event__c/Thread_Event__c.object-meta.xml
<CustomObject>
    <label>Thread Event</label>
    <nameField>
        <label>Thread Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thread Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread_Event__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <inlineHelpText>User feedback for a specific event</inlineHelpText>
    <label>Feedback</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Function_Correction__c.field-meta.xml
<CustomField>
    <fullName>Function_Correction__c</fullName>
    <description>User Corrections for Function Call JSON</description>
    <label>Function Correction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Thread__c.field-meta.xml
<CustomField>
    <fullName>Thread__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meta</fullName>
                <default>true</default>
                <label>Meta</label>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ThreadSelector.cls
public with sharing class ThreadSelector {

    public static Thread__c getThread(Id threadId) {
        return [
                SELECT Id,
                        Name,
                        External_Id__c,
                        Model__c,
                        Status__c,
                        Run_Id__c,
                        Ended_At__c,
                (
                        SELECT Id,
                                Thread__c,
                                External_Id__c,
                                Name,
                                Type__c,
                                Body__c,
                                CreatedById,
                                CreatedBy.Name,
                                CreatedBy.Alias,
                                CreatedDate,
                                Function_Correction__c,
                                Feedback__c
                        FROM Events__r
                        ORDER BY CreatedDate ASC
                        LIMIT 500
                )
                FROM Thread__c
                WHERE Id =: threadId
        ];
    }

    public static Thread_Event__c getThreadEvent(Id threadId) {
        return [
                SELECT Id,
                        Thread__c,
                        External_Id__c,
                        Name,
                        Type__c,
                        Body__c,
                        CreatedById,
                        CreatedBy.Name,
                        CreatedBy.Alias,
                        CreatedDate,
                        Function_Correction__c,
                        Feedback__c
                FROM Thread_Event__c
                WHERE Id =: threadId
                LIMIT 1
        ];
    }

    public static Thread_Event__c[] getThreadEvents(Id[] threadIds) {
        return [
                SELECT Id,
                        Thread__c,
                        External_Id__c,
                        Name,
                        Type__c,
                        Body__c,
                        CreatedById,
                        CreatedBy.Name,
                        CreatedBy.Alias,
                        CreatedDate,
                        Function_Correction__c,
                        Feedback__c
                FROM Thread_Event__c
                WHERE Id IN :threadIds
        ];
    }
}