force-app/main/default/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <label>Thread</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Thread Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <inlineHelpText>User Feedback on Thread</inlineHelpText>
    <label>Feedback</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/Thread_Event__c.object-meta.xml
<CustomObject>
    <label>Thread Event</label>
    <nameField>
        <label>Thread Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thread Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread_Event__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <inlineHelpText>User feedback for a specific event</inlineHelpText>
    <label>Feedback</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Function_Correction__c.field-meta.xml
<CustomField>
    <fullName>Function_Correction__c</fullName>
    <description>User Corrections for Function Call JSON</description>
    <label>Function Correction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Thread__c.field-meta.xml
<CustomField>
    <fullName>Thread__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Meta</fullName>
                <default>true</default>
                <label>Meta</label>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>Function</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ThreadEventWrapper.cls
public with sharing class ThreadEventWrapper {

    @AuraEnabled public String threadId { get; set; }
    @AuraEnabled public String externalId { get; set; }
    @AuraEnabled public String salesforceId { get; set; }
    @AuraEnabled public String name { get; set; }
    @AuraEnabled public Actor actor { get; set; }
    @AuraEnabled public String type { get; set; }
    @AuraEnabled public String subtype { get; set; }
    @AuraEnabled public String status { get; set; }
    @AuraEnabled public String body { get; set; }
    @AuraEnabled public String correction { get; set; }
    @AuraEnabled public String feedback { get; set; }
    @AuraEnabled public Long eventTime { get; set; }

    public class Actor {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String alias { get; set; }
        @AuraEnabled public String role { get; set; }

        public Actor() {}

        public Actor(String role) {
            this.role = role;
        }

        public Actor(User u) {
            this.id = u.Id;
            this.name = u.Name;
            this.alias = u.Alias;
            this.role = 'user';
        }
    }

    public ThreadEventWrapper() {}

    public ThreadEventWrapper(Thread_Event__c threadEvent) {
        this.threadId = threadEvent.Thread__c;
        this.externalId = threadEvent.External_Id__c;
        this.salesforceId = threadEvent.Id;
        this.name = threadEvent.Name;
        this.actor = new Actor(threadEvent.CreatedBy);
        this.type = threadEvent.Type__c;
        this.body = threadEvent.Body__c;
        this.correction = threadEvent.Function_Correction__c;
        this.feedback = threadEvent.Feedback__c;
        this.eventTime = threadEvent.CreatedDate?.getTime();
    }

    public Thread_Event__c unwrap() {
        Thread_Event__c threadEvent = new Thread_Event__c();
        if (this.salesforceId != null) {
            threadEvent.Id = this.salesforceId;
        }
        threadEvent.Thread__c = this.threadId;
        threadEvent.External_Id__c = this.externalId;
        threadEvent.Type__c = this.type;
        threadEvent.Body__c = this.body;
        threadEvent.Function_Correction__c = this.correction;
        threadEvent.Feedback__c = this.feedback;
        return threadEvent;
    }

    public static ThreadEventWrapper[] wrap(Thread_Event__c[] threadEvents) {
        ThreadEventWrapper[] res = new List<ThreadEventWrapper>();
        if (threadEvents != null && !threadEvents.isEmpty()) {
            for (Integer i = 0; i < threadEvents.size(); i++) {
                res.add(new ThreadEventWrapper(threadEvents[i]));
            }
        }
        return res;
    }
}