force-app/main/default/objects/Thread__c/Thread__c.object-meta.xml
<CustomObject>
    <label>Thread</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Thread Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Threads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread__c/fields/Ended_At__c.field-meta.xml
<CustomField>
    <fullName>Ended_At__c</fullName>
    <label>Ended At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>gpt-4</fullName>
            </value>
            <value>
                <fullName>gpt-4-turbo-preview</fullName>
            </value>
            <value>
                <fullName>gpt-3.5-turbo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Run_Id__c.field-meta.xml
<CustomField>
    <fullName>Run_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Chat GPT External Id for a &quot;Run&quot;</inlineHelpText>
    <label>Run Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Thread__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Thread_Event__c/Thread_Event__c.object-meta.xml
<CustomObject>
    <label>Thread Event</label>
    <nameField>
        <label>Thread Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thread Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Thread_Event__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Thread_Event__c/fields/Thread__c.field-meta.xml
<CustomField>
    <fullName>Thread__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Thread</label>
    <referenceTo>Thread__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ThreadWrapper.cls
public with sharing class ThreadWrapper {

    @AuraEnabled public String externalId { get; set; }
    @AuraEnabled public String salesforceId { get; set; }
    @AuraEnabled public String assistantId { get; set; }
    @AuraEnabled public String name { get; set; }
    @AuraEnabled public String model { get; set; }
    @AuraEnabled public String status { get; set; }
    @AuraEnabled public String runId { get; set; }
    @AuraEnabled public Long runExpiresAt { get; set; }
    @AuraEnabled public Long endedAt { get; set; }
    @AuraEnabled public ThreadEventWrapper[] threadEvents { get; set; }
    @AuraEnabled public String toolsJson { get; set; }

    public ThreadWrapper(Thread__c thread) {
        System.debug('Wrapping Thread:' + JSON.serialize(thread));
        this.salesforceId = thread.Id;
        this.name = thread.Name;
        this.externalId = thread.External_Id__c;
        this.model = thread.Model__c;
        this.status = thread.Status__c;
        this.runId = thread.Run_Id__c;
        this.endedAt = thread.Ended_At__c?.getTime();
        this.threadEvents = new List<ThreadEventWrapper>();

        if (thread.Events__r != null && !thread.Events__r.isEmpty()) {
            for (Integer i = 0; i < thread.Events__r.size(); i++) {
                threadEvents.add(new ThreadEventWrapper(thread.Events__r[i]));
            }
        }
    }

    public ThreadWrapper(OpenAiThread thread) {

    }

    public ThreadWrapper(OpenAiThreadRun threadRun) {
        this.externalId = threadRun.thread_id;
        this.runId = threadRun.id;
        this.assistantId = threadRun.assistant_id;
        this.status = threadRun.status;
        this.runExpiresAt = threadRun.expires_at;
        this.model = threadRun.model;
        this.toolsJson = JSON.serialize(threadRun.tools);
    }
}